repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.8.0
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.1
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
  - repo: local
    hooks:
      - id: python-compileall
        name: python compileall
        entry: python -m compileall python-packages services
        language: system
        pass_filenames: false
